# fly.toml app configuration file generated for bookmark-manager on 2023-05-16T22:09:01+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookmark-manager"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"
processes = []

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "bookmark-manager"
  DB_HOST = "solitary-wildflower-380.interna"
  DB_PORT = "3306"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
